parameters:
#    infinity_games_connexion.example.class: InfinityGames\ConnexionBundle\Example

services:
#    infinity_games_connexion.example:
#        class: %infinity_games_connexion.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
