infinity_games_accueil_homepage:
    pattern:  accueil/
    defaults: { _controller: InfinityGamesAccueilBundle:Default:index }
infinity_games_accueil_homepage:
    pattern:  administration/
    defaults: { _controller: InfinityGamesInfinityBundle:Administration:index }
