infinity_games_infinity_homepage:
    pattern:  /accueil
    defaults: { _controller: InfinityGamesInfinityBundle:Default:index }
InfinityGamesInfinityBundle_jeu:
        resource: "@InfinityGamesInfinityBundle/Resources/config/routing/jeu.yml"
        prefix:   /jeu
InfinityGamesInfinityBundle_forumcategorie:
        resource: "@InfinityGamesInfinityBundle/Resources/config/routing/forumcategorie.yml"
        prefix:   /forumcategorie
InfinityGamesInfinityBundle_genrejeu:
        resource: "@InfinityGamesInfinityBundle/Resources/config/routing/genrejeu.yml"
        prefix:   /genrejeu
InfinityGamesInfinityBundle_messageinterne:
        resource: "@InfinityGamesInfinityBundle/Resources/config/routing/messageinterne.yml"
        prefix:   /messageinterne
InfinityGamesInfinityBundle_niveaucreation:
        resource: "@InfinityGamesInfinityBundle/Resources/config/routing/niveaucreation.yml"
        prefix:   /niveaucreation
InfinityGamesInfinityBundle_niveauexperience:
        resource: "@InfinityGamesInfinityBundle/Resources/config/routing/niveauexperience.yml"
        prefix:   /niveauexperience
InfinityGamesInfinityBundle_typeitemstore:
        resource: "@InfinityGamesInfinityBundle/Resources/config/routing/typeitemstore.yml"
        prefix:   /typeitemstore
InfinityGamesInfinityBundle_utilisateur:
        resource: "@InfinityGamesInfinityBundle/Resources/config/routing/utilisateur.yml"
        prefix:   /utilisateur
InfinityGamesInfinityBundle_messageforum:
        resource: "@InfinityGamesInfinityBundle/Resources/config/routing/messageforum.yml"
        prefix:   /messageforum
infinity_games_infinity_contact:
    pattern:  /contact
    defaults: { _controller: InfinityGamesInfinityBundle:Mailer:index }
infinity_games_infinity_classement_general:
    pattern:  /classement
    defaults: { _controller: InfinityGamesInfinityBundle:Classement:index }
InfinityGamesInfinityBundle_descripifitemstore:
    resource: "@InfinityGamesInfinityBundle/Resources/config/routing/descripifitemstore.yml"
    prefix:   /descripifitemstore
InfinityGamesInfinityBundle_commande:
    resource: "@InfinityGamesInfinityBundle/Resources/config/routing/commande.yml"
    prefix:   /commande
infinity_games_infinity_panier_affichage:
    pattern:  /panier
    defaults: { _controller: InfinityGamesInfinityBundle:Panier:index }
infinity_games_infinity_ajout_produit:
    pattern:  /panier/add/{id}
    defaults: { _controller: InfinityGamesInfinityBundle:Panier:addProduit }
infinity_games_infinity_supprimer_panier:
    pattern:  /panier/clean
    defaults: { _controller: InfinityGamesInfinityBundle:Panier:viderPanier }
infinity_games_infinity_supprimer_produit:
    pattern:  /panier/suppr/{id}
    defaults: { _controller: InfinityGamesInfinityBundle:Panier:supprProduit }
infinity_games_infinity_validation_commande:
    pattern:  /panier/validation
    defaults: { _controller: InfinityGamesInfinityBundle:Panier:validationPanier }
infinity_games_infinity_modifie_add:
    pattern:  /panier/increment/{id}
    defaults: { controller: InfinityGamesInfinityBundle:Panier:incrementQtt }
InfinityGamesInfinityBundle_statsutilisateur:
        resource: "@InfinityGamesInfinityBundle/Resources/config/routing/statsutilisateur.yml"
        prefix:   /statsutilisateur
InfinityGamesInfinityBundle_categoriefactory:
        resource: "@InfinityGamesInfinityBundle/Resources/config/routing/categoriefactory.yml"
        prefix:   /categoriefactory
InfinityGamesInfinityBundle_articlesfactory:
        resource: "@InfinityGamesInfinityBundle/Resources/config/routing/articlesfactory.yml"
        prefix:   /articlesfactory
infinity_games_infinity_factory:
    pattern:  /factory
    defaults: { _controller: InfinityGamesInfinityBundle:CategorieFactory:affichageIndex }
infinity_games_test_maintenance:
    pattern:  /maintenance
    defaults: { _controller: InfinityGamesInfinityBundle:Administration:countUtilisateurs }
InfinityGamesInfinityBundle_articlestodolist:
        resource: "@InfinityGamesInfinityBundle/Resources/config/routing/articlestodolist.yml"
        prefix:   /articlestodolist
InfinityGamesInfinityBundle_liaisonitemuser:
        resource: "@InfinityGamesInfinityBundle/Resources/config/routing/liaisonitemuser.yml"
        prefix:   /liaisonitemuser
InfinityGamesInfinityBundle_top_score_jeu:
        resource: "@InfinityGamesInfinityBundle/Resources/config/routing/top_score_jeu.yml"
        prefix:   /top_score_jeu