jeu:
    pattern:  /
    defaults: { _controller: "InfinityGamesInfinityBundle:Jeu:index" }

jeu_show:
    pattern:  /{id}/show
    defaults: { _controller: "InfinityGamesInfinityBundle:Jeu:show" }

jeu_new:
    pattern:  /new
    defaults: { _controller: "InfinityGamesInfinityBundle:Jeu:new" }

jeu_create:
    pattern:  /create
    defaults: { _controller: "InfinityGamesInfinityBundle:Jeu:create" }
    requirements: { _method: post }

jeu_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "InfinityGamesInfinityBundle:Jeu:edit" }

jeu_update:
    pattern:  /{id}/update
    defaults: { _controller: "InfinityGamesInfinityBundle:Jeu:update" }
    requirements: { _method: post }

jeu_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "InfinityGamesInfinityBundle:Jeu:delete" }
    requirements: { _method: post }
jeu_catalogue:
    pattern:  /catalogue
    defaults: { _controller: "InfinityGamesInfinityBundle:Jeu:catalogue" }
jeu_redirect:
    pattern:  /redirect
    defaults: { _controller: "InfinityGamesInfinityBundle:Jeu:landingIndexJeu" }
