parameters:
#    infinity_games_inscription.example.class: InfinityGames\InscriptionBundle\Example

services:
#    infinity_games_inscription.example:
#        class: %infinity_games_inscription.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
